---
galaxy_info:
  author: "Alexander Ivanov"
  description: "Install and configure MariaDB (MySQL) on Debian"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
dependencies: []
