branches:
  - name: staging
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ['build-and-test']
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: production
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ['build-and-test']
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
