#!/bin/bash

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Ensure inventory directory exists
mkdir -p "${SCRIPT_DIR}/inventory"

# Ensure .gitignore exists
touch "${SCRIPT_DIR}/../.gitignore"

# Prompt for production server IP
while true; do
    read -p "Enter production server IP address: " production_server_ip
    if [[ $production_server_ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        break
    else
        echo -e "${RED}Invalid IP address format. Please try again.${NC}"
    fi
done

# Prompt for initial SSH port
while true; do
    read -p "Enter current SSH port (default: 22): " connection_port
    connection_port=${connection_port:-22}
    if [[ $connection_port =~ ^[0-9]+$ ]] && [ $connection_port -ge 1 ] && [ $connection_port -le 65535 ]; then
        break
    else
        echo -e "${RED}Invalid port number. Please enter a number between 1 and 65535.${NC}"
    fi
done

# Prompt for new SSH port
while true; do
    read -p "Enter new SSH port (default: ${connection_port}): " ssh_port
    ssh_port=${ssh_port:-$connection_port}
    if [[ $ssh_port =~ ^[0-9]+$ ]] && [ $ssh_port -ge 1 ] && [ $ssh_port -le 65535 ]; then
        break
    else
        echo -e "${RED}Invalid port number. Please enter a number between 1 and 65535.${NC}"
    fi
done

# Prompt for SSH key name
while true; do
    read -p "Enter SSH key name (without .pub extension): " ssh_key_name
    if [ -n "$ssh_key_name" ]; then
        if [ -f "$HOME/.ssh/$ssh_key_name" ] && [ -f "$HOME/.ssh/$ssh_key_name.pub" ]; then
            break
        else
            echo -e "${RED}SSH key files not found. Please check the key name and try again.${NC}"
        fi
    else
        echo -e "${RED}SSH key name cannot be empty.${NC}"
    fi
done

# Create configuration file
cat > "${SCRIPT_DIR}/inventory/production.cfg" << EOF
# DO NOT EDIT THIS FILE MANUALLY
# To change configuration, run setup-production.sh script
production_server_ip: $production_server_ip
connection_port: $connection_port
ssh_port: $ssh_port
ssh_key_name: $ssh_key_name
EOF

echo -e "${GREEN}Configuration saved to ${SCRIPT_DIR}/inventory/production.cfg${NC}"

# Add to .gitignore if not already there
if ! grep -q "infra/inventory/production.cfg" "${SCRIPT_DIR}/../.gitignore"; then
    echo "infra/inventory/production.cfg" >> "${SCRIPT_DIR}/../.gitignore"
    echo -e "${GREEN}Added production.cfg to .gitignore${NC}"
fi

# Make script executable
chmod +x "$0" 