# Main playbook that applies all roles to hosts in 'all'
- name: Deploy web stack on all servers
  hosts: all
  gather_facts: true
  become: true

  roles:
    - role: common
      tags: common
    - role: mysql
      tags: mysql
    - role: php
      tags: php
    - role: nginx
      tags: nginx
    # - role: frontend
    #   tags: frontend
