# Main playbook for deploying web stack

- name: Deploy web stack on all servers
  hosts: all
  vars_files:
    - inventory/production.cfg

  roles:
    - common
    # - role: mysql
    #   tags: mysql
    # - role: php
    #   tags: php
    # - role: nginx
    #   tags: nginx
    # - role: frontend
    #   tags: frontend
