# Main playbook for deploying web stack

- name: Deploy web stack on all servers
  hosts: all
  vars_files:
    - inventory/production.cfg

  roles:
    - common
    # - role: mysql
    #   tags: mysql
    # - role: php
    #   tags: php
    # - role: nginx
    #   tags: nginx
    # - role: frontend
    #   tags: frontend

- name: Apply security configurations only on production servers
  hosts: all
  vars_files:
    - inventory/production.cfg
  tasks:
    - name: Include security role
      include_role:
        name: security
      when: inventory_file is search('production') or inventory_hostname is search('production')
      tags: security

- name: Install Monitoring only on production servers
  hosts: all
  vars_files:
    - inventory/production.cfg
  tasks:
    - name: Include monitoring role
      include_role:
        name: monitoring
      when: inventory_file is search('production') or inventory_hostname is search('production')
      tags: monitoring
