---
# Handlers for PHP role

- name: Restart PHP-FPM
  ansible.builtin.service:
    name: php8.2-fpm
    state: restarted
  when: ansible_service_mgr == 'systemd'

- name: Restart PHP-FPM manually
  ansible.builtin.shell: |
    pkill php-fpm || true
    nohup /usr/sbin/php-fpm8.2 \
      --nodaemonize \
      --fpm-config /etc/php/8.2/fpm/php-fpm.conf \
      > /var/log/php-fpm-manual.log 2>&1 &
  when: ansible_service_mgr != 'systemd'
  changed_when: true
