---
# Install and configure Nginx

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  when: ansible_service_mgr == 'systemd'

- name: Create Nginx directories in non-systemd environment
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  loop:
    - /run/nginx
    - /var/log/nginx
  when: ansible_service_mgr != 'systemd'

- name: Start Nginx manually in non-systemd environment
  ansible.builtin.shell: |
    nohup /usr/sbin/nginx \
      -c /etc/nginx/nginx.conf \
      > /var/log/nginx-manual.log 2>&1 &
  args:
    creates: /run/nginx.pid
  async: 10
  poll: 0
  when: ansible_service_mgr != 'systemd'

- name: Wait until Nginx port is available
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 80
    state: started
    timeout: 30

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Reload Nginx
    - Reload Nginx manually

- name: Copy Nginx main configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload Nginx
    - Reload Nginx manually

- name: Copy Nginx site configuration
  ansible.builtin.template:
    src: site.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_site_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload Nginx
    - Reload Nginx manually

- name: Enable Nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nginx_site_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_site_name }}.conf"
    state: link
  notify:
    - Reload Nginx
    - Reload Nginx manually

- name: Create web root directory
  ansible.builtin.file:
    path: "{{ nginx_web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Create a test index.php file
  ansible.builtin.template:
    src: index.php.j2
    dest: "{{ nginx_web_root }}/index.php"
    owner: www-data
    group: www-data
    mode: "0644"
  when: nginx_create_test_page | bool
