---
# Frontend role handlers

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: ansible_service_mgr == 'systemd'

- name: Reload Nginx manually
  ansible.builtin.command: nginx -s reload
  changed_when: true
  when: ansible_service_mgr != 'systemd'

- name: Restart Frontend
  ansible.builtin.service:
    name: pm2-{{ frontend_app_name }}
    state: restarted
  when: ansible_service_mgr == 'systemd'

- name: Restart Frontend manually
  ansible.builtin.command: pm2 restart {{ frontend_app_name }}
  changed_when: true
  when: ansible_service_mgr != 'systemd'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'
