---
# infra/roles/common/tasks/main.yml

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Ensure .ssh directory exists for root
  ansible.builtin.file:
    path: "/root/.ssh"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Copy public key to authorized_keys for root
  ansible.builtin.copy:
    src: "{{ common_deploy_user_key }}"
    dest: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: "0600"

- name: Ensure UFW is enabled and allow SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
    state: enabled
