---
# Fail2ban security tasks

- name: Ensure Fail2ban is installed
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Ensure configuration directory exists
  ansible.builtin.file:
    path: /etc/fail2ban/jail.d
    state: directory
    mode: '0755'

- name: Configure Fail2ban SSH settings
  ansible.builtin.template:
    src: ssh-jail.conf.j2
    dest: /etc/fail2ban/jail.d/ssh-custom.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Fail2ban

- name: Ensure Fail2ban service is running and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes 