---
# UFW security tasks

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Reset all UFW rules
  ansible.builtin.shell: ufw --force reset
  changed_when: true

- name: Get SSH port from production.cfg
  ansible.builtin.set_fact:
    custom_ssh_port: "{{ ssh_port }}"

- name: Ensure UFW is enabled and allow SSH on custom port
  community.general.ufw:
    rule: allow
    port: "{{ custom_ssh_port }}"
    proto: tcp
    state: enabled

# Add more common firewall rules
- name: Configure basic UFW rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { rule: 'allow', port: '80', proto: 'tcp' }    # HTTP
    - { rule: 'allow', port: '443', proto: 'tcp' }   # HTTPS
    - { rule: 'allow', port: '123', proto: 'udp' }    # NTP
  notify: Reload UFW 