---
# Install Netdata using official kickstart script
- name: Download Netdata kickstart script
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /tmp/netdata-kickstart.sh
    mode: '0755'
  become: yes

- name: Run Netdata kickstart script
  shell: |
    /tmp/netdata-kickstart.sh --disable-telemetry
  args:
    creates: /usr/sbin/netdata
  become: yes

- name: Disable anonymous statistics
  file:
    path: /etc/netdata/.opt-out-from-anonymous-statistics
    state: touch
    mode: '0644'
  become: yes

- name: Ensure Netdata service is running and enabled
  systemd:
    name: netdata
    state: started
    enabled: yes

