name: Deploy to Production

on:
  push:
    tags: ['v*']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating GitHub releases
    environment:
      name: production
      url: ${{ vars.PRODUCTION_URL }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Get current timestamp
        id: get_timestamp
        run: echo "timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build for production
        env:
          APP_VERSION: ${{ steps.get_version.outputs.version }}
        run: npx nx build client --configuration=production --base-href=/new/

      - name: Create build archive
        run: |
          cd dist/apps/client
          tar -czf ../../../drevo-web-${{ steps.get_version.outputs.version }}.tar.gz *
          cd ../../..

      - name: Deploy with reusable action
        uses: ./.github/actions/deploy
        with:
          environment: 'production'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-port: ${{ secrets.SSH_PORT || '22' }}
          source-path: 'dist/apps/client'
          target-path: 'production'
          environment-url: ${{ vars.PRODUCTION_URL }}
          version: ${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: |
            🚀 **Production Release ${{ steps.get_version.outputs.version }}**
            
            **Deployed**: ${{ steps.get_timestamp.outputs.timestamp }}
            **Environment**: Production
            **URL**: ${{ vars.PRODUCTION_URL }}
            
            **Changes in this release:**
            - See commit history for detailed changes
            
            **Deployment**: ✅ Files deployed successfully
            
            **Download:**
            - 📦 `drevo-web-${{ steps.get_version.outputs.version }}.tar.gz` - Production build archive
          draft: false
          prerelease: false
          files: |
            drevo-web-${{ steps.get_version.outputs.version }}.tar.gz

      - name: Notify deployment
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Production deployment successful: ${{ vars.PRODUCTION_URL }}"
            echo "🎉 Release ${{ steps.get_version.outputs.version }} is live!"
          else
            echo "❌ Production deployment failed"
            echo "🚨 Manual intervention required"
            exit 1
          fi