name: Cleanup Branches

on:
  pull_request:
    types: [closed]

permissions:
  contents: write # Required for branch deletion

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.head.ref, 'staging') && !contains(github.event.pull_request.head.ref, 'production')
    steps:
      - name: Delete merged branch
        run: |
          gh api \
            --method DELETE \
            repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
